### PR TITLE
VPSADEV-146: Added label to row counter

### PR DESCRIPTION
**Pull request by sherakama**

### CODE REVIEW

**Comment by sherakama** [comment]
@cynmij, Please review to ensure the main manage content has the label 'Row' for the row count.

**Comment by sherakama** [comment]
I have also added VBO options for VPSADEV-130

**Comment by sherakama** [comment]
@cynmij,

Please to review.

**Comment by cynmij** [comment]
Looks great!  Anything else on VPSADEV-146?  Delete branch?

**Pull request merged**
